[project]
name = "frontend-prototype-server"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "fastapi>=0.116.1",
  "httpx>=0.28.1",
  "pydantic>=2.11.7",
  "python-multipart>=0.0.20",
  "uvicorn[standard]>=0.35.0"
]

[dependency-groups]
dev = [
  "pytest>=8.4.2"
]
